on:
  push:
    branches:
      - dependabot/npm_and_yarn/**
  pull_request:
    branches:
      - dependabot/npm_and_yarn/**
name: 'Dependabot Lockfile Update'
permissions:
  contents: write
jobs:
  update-yarn-lock:
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: ${{ secrets.DEPENDABOT_SSH_DEPLOY_KEY }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '20.11'
      - name: 'Configure Git with deploy key'
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: 'Install dependencies'
        run: yarn install
      - name: 'Commit yarn.lock'
        env:
          message: "chore(dependabot): Update yarn.lock file | [dependabot skip]"
        run: |
          git config --global user.name 'dependabot[bot]'
          git config --global user.email 'dependabot[bot]@users.noreply.github.com'
          git diff --quiet || (git add yarn.lock && git commit -m "$message")
      - name: 'Push changes'
        run: |
          git push
